/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestPgliteRouteImport } from './routes/test-pglite'
import { Route as TempDbRequiredRouteImport } from './routes/_tempDbRequired'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TempDbRequiredProjectsRouteImport } from './routes/_tempDbRequired.projects'
import { Route as TempDbRequiredProjectRootRouteImport } from './routes/_tempDbRequired.project-root'
import { Route as TempDbRequiredProjectsIndexRouteImport } from './routes/_tempDbRequired.projects.index'
import { Route as TempDbRequiredProjectsProjectIdRouteImport } from './routes/_tempDbRequired.projects.$projectId'

const TestPgliteRoute = TestPgliteRouteImport.update({
  id: '/test-pglite',
  path: '/test-pglite',
  getParentRoute: () => rootRouteImport,
} as any)
const TempDbRequiredRoute = TempDbRequiredRouteImport.update({
  id: '/_tempDbRequired',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TempDbRequiredProjectsRoute = TempDbRequiredProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => TempDbRequiredRoute,
} as any)
const TempDbRequiredProjectRootRoute =
  TempDbRequiredProjectRootRouteImport.update({
    id: '/project-root',
    path: '/project-root',
    getParentRoute: () => TempDbRequiredRoute,
  } as any)
const TempDbRequiredProjectsIndexRoute =
  TempDbRequiredProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TempDbRequiredProjectsRoute,
  } as any)
const TempDbRequiredProjectsProjectIdRoute =
  TempDbRequiredProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => TempDbRequiredProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-pglite': typeof TestPgliteRoute
  '/project-root': typeof TempDbRequiredProjectRootRoute
  '/projects': typeof TempDbRequiredProjectsRouteWithChildren
  '/projects/$projectId': typeof TempDbRequiredProjectsProjectIdRoute
  '/projects/': typeof TempDbRequiredProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-pglite': typeof TestPgliteRoute
  '/project-root': typeof TempDbRequiredProjectRootRoute
  '/projects/$projectId': typeof TempDbRequiredProjectsProjectIdRoute
  '/projects': typeof TempDbRequiredProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tempDbRequired': typeof TempDbRequiredRouteWithChildren
  '/test-pglite': typeof TestPgliteRoute
  '/_tempDbRequired/project-root': typeof TempDbRequiredProjectRootRoute
  '/_tempDbRequired/projects': typeof TempDbRequiredProjectsRouteWithChildren
  '/_tempDbRequired/projects/$projectId': typeof TempDbRequiredProjectsProjectIdRoute
  '/_tempDbRequired/projects/': typeof TempDbRequiredProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-pglite'
    | '/project-root'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-pglite'
    | '/project-root'
    | '/projects/$projectId'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_tempDbRequired'
    | '/test-pglite'
    | '/_tempDbRequired/project-root'
    | '/_tempDbRequired/projects'
    | '/_tempDbRequired/projects/$projectId'
    | '/_tempDbRequired/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TempDbRequiredRoute: typeof TempDbRequiredRouteWithChildren
  TestPgliteRoute: typeof TestPgliteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-pglite': {
      id: '/test-pglite'
      path: '/test-pglite'
      fullPath: '/test-pglite'
      preLoaderRoute: typeof TestPgliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tempDbRequired': {
      id: '/_tempDbRequired'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TempDbRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tempDbRequired/projects': {
      id: '/_tempDbRequired/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof TempDbRequiredProjectsRouteImport
      parentRoute: typeof TempDbRequiredRoute
    }
    '/_tempDbRequired/project-root': {
      id: '/_tempDbRequired/project-root'
      path: '/project-root'
      fullPath: '/project-root'
      preLoaderRoute: typeof TempDbRequiredProjectRootRouteImport
      parentRoute: typeof TempDbRequiredRoute
    }
    '/_tempDbRequired/projects/': {
      id: '/_tempDbRequired/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof TempDbRequiredProjectsIndexRouteImport
      parentRoute: typeof TempDbRequiredProjectsRoute
    }
    '/_tempDbRequired/projects/$projectId': {
      id: '/_tempDbRequired/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof TempDbRequiredProjectsProjectIdRouteImport
      parentRoute: typeof TempDbRequiredProjectsRoute
    }
  }
}

interface TempDbRequiredProjectsRouteChildren {
  TempDbRequiredProjectsProjectIdRoute: typeof TempDbRequiredProjectsProjectIdRoute
  TempDbRequiredProjectsIndexRoute: typeof TempDbRequiredProjectsIndexRoute
}

const TempDbRequiredProjectsRouteChildren: TempDbRequiredProjectsRouteChildren =
  {
    TempDbRequiredProjectsProjectIdRoute: TempDbRequiredProjectsProjectIdRoute,
    TempDbRequiredProjectsIndexRoute: TempDbRequiredProjectsIndexRoute,
  }

const TempDbRequiredProjectsRouteWithChildren =
  TempDbRequiredProjectsRoute._addFileChildren(
    TempDbRequiredProjectsRouteChildren,
  )

interface TempDbRequiredRouteChildren {
  TempDbRequiredProjectRootRoute: typeof TempDbRequiredProjectRootRoute
  TempDbRequiredProjectsRoute: typeof TempDbRequiredProjectsRouteWithChildren
}

const TempDbRequiredRouteChildren: TempDbRequiredRouteChildren = {
  TempDbRequiredProjectRootRoute: TempDbRequiredProjectRootRoute,
  TempDbRequiredProjectsRoute: TempDbRequiredProjectsRouteWithChildren,
}

const TempDbRequiredRouteWithChildren = TempDbRequiredRoute._addFileChildren(
  TempDbRequiredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TempDbRequiredRoute: TempDbRequiredRouteWithChildren,
  TestPgliteRoute: TestPgliteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
