/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TempDbRequiredRouteImport } from './routes/_tempDbRequired'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTodoItemsRouteImport } from './routes/api.todo-items'
import { Route as ApiTempDbRouteImport } from './routes/api.temp-db'
import { Route as ApiProjectsRouteImport } from './routes/api.projects'
import { Route as ApiGetTempIdRouteImport } from './routes/api.get-temp-id'
import { Route as ApiCleanupRouteImport } from './routes/api.cleanup'
import { Route as ApiBoardsRouteImport } from './routes/api.boards'
import { Route as TempDbRequiredProjectsRouteImport } from './routes/_tempDbRequired.projects'
import { Route as TempDbRequiredProjectsIndexRouteImport } from './routes/_tempDbRequired.projects.index'
import { Route as ApiGetBoardsRouteImport } from './routes/api.get.boards'
import { Route as TempDbRequiredProjectsProjectIdRouteImport } from './routes/_tempDbRequired.projects.$projectId'

const TempDbRequiredRoute = TempDbRequiredRouteImport.update({
  id: '/_tempDbRequired',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodoItemsRoute = ApiTodoItemsRouteImport.update({
  id: '/api/todo-items',
  path: '/api/todo-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTempDbRoute = ApiTempDbRouteImport.update({
  id: '/api/temp-db',
  path: '/api/temp-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetTempIdRoute = ApiGetTempIdRouteImport.update({
  id: '/api/get-temp-id',
  path: '/api/get-temp-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCleanupRoute = ApiCleanupRouteImport.update({
  id: '/api/cleanup',
  path: '/api/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardsRoute = ApiBoardsRouteImport.update({
  id: '/api/boards',
  path: '/api/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const TempDbRequiredProjectsRoute = TempDbRequiredProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => TempDbRequiredRoute,
} as any)
const TempDbRequiredProjectsIndexRoute =
  TempDbRequiredProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TempDbRequiredProjectsRoute,
  } as any)
const ApiGetBoardsRoute = ApiGetBoardsRouteImport.update({
  id: '/api/get/boards',
  path: '/api/get/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const TempDbRequiredProjectsProjectIdRoute =
  TempDbRequiredProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => TempDbRequiredProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof TempDbRequiredProjectsRouteWithChildren
  '/api/boards': typeof ApiBoardsRoute
  '/api/cleanup': typeof ApiCleanupRoute
  '/api/get-temp-id': typeof ApiGetTempIdRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/temp-db': typeof ApiTempDbRoute
  '/api/todo-items': typeof ApiTodoItemsRoute
  '/projects/$projectId': typeof TempDbRequiredProjectsProjectIdRoute
  '/api/get/boards': typeof ApiGetBoardsRoute
  '/projects/': typeof TempDbRequiredProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/boards': typeof ApiBoardsRoute
  '/api/cleanup': typeof ApiCleanupRoute
  '/api/get-temp-id': typeof ApiGetTempIdRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/temp-db': typeof ApiTempDbRoute
  '/api/todo-items': typeof ApiTodoItemsRoute
  '/projects/$projectId': typeof TempDbRequiredProjectsProjectIdRoute
  '/api/get/boards': typeof ApiGetBoardsRoute
  '/projects': typeof TempDbRequiredProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tempDbRequired': typeof TempDbRequiredRouteWithChildren
  '/_tempDbRequired/projects': typeof TempDbRequiredProjectsRouteWithChildren
  '/api/boards': typeof ApiBoardsRoute
  '/api/cleanup': typeof ApiCleanupRoute
  '/api/get-temp-id': typeof ApiGetTempIdRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/temp-db': typeof ApiTempDbRoute
  '/api/todo-items': typeof ApiTodoItemsRoute
  '/_tempDbRequired/projects/$projectId': typeof TempDbRequiredProjectsProjectIdRoute
  '/api/get/boards': typeof ApiGetBoardsRoute
  '/_tempDbRequired/projects/': typeof TempDbRequiredProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/api/boards'
    | '/api/cleanup'
    | '/api/get-temp-id'
    | '/api/projects'
    | '/api/temp-db'
    | '/api/todo-items'
    | '/projects/$projectId'
    | '/api/get/boards'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/boards'
    | '/api/cleanup'
    | '/api/get-temp-id'
    | '/api/projects'
    | '/api/temp-db'
    | '/api/todo-items'
    | '/projects/$projectId'
    | '/api/get/boards'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_tempDbRequired'
    | '/_tempDbRequired/projects'
    | '/api/boards'
    | '/api/cleanup'
    | '/api/get-temp-id'
    | '/api/projects'
    | '/api/temp-db'
    | '/api/todo-items'
    | '/_tempDbRequired/projects/$projectId'
    | '/api/get/boards'
    | '/_tempDbRequired/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TempDbRequiredRoute: typeof TempDbRequiredRouteWithChildren
  ApiBoardsRoute: typeof ApiBoardsRoute
  ApiCleanupRoute: typeof ApiCleanupRoute
  ApiGetTempIdRoute: typeof ApiGetTempIdRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiTempDbRoute: typeof ApiTempDbRoute
  ApiTodoItemsRoute: typeof ApiTodoItemsRoute
  ApiGetBoardsRoute: typeof ApiGetBoardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tempDbRequired': {
      id: '/_tempDbRequired'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TempDbRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todo-items': {
      id: '/api/todo-items'
      path: '/api/todo-items'
      fullPath: '/api/todo-items'
      preLoaderRoute: typeof ApiTodoItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/temp-db': {
      id: '/api/temp-db'
      path: '/api/temp-db'
      fullPath: '/api/temp-db'
      preLoaderRoute: typeof ApiTempDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get-temp-id': {
      id: '/api/get-temp-id'
      path: '/api/get-temp-id'
      fullPath: '/api/get-temp-id'
      preLoaderRoute: typeof ApiGetTempIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cleanup': {
      id: '/api/cleanup'
      path: '/api/cleanup'
      fullPath: '/api/cleanup'
      preLoaderRoute: typeof ApiCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/boards': {
      id: '/api/boards'
      path: '/api/boards'
      fullPath: '/api/boards'
      preLoaderRoute: typeof ApiBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tempDbRequired/projects': {
      id: '/_tempDbRequired/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof TempDbRequiredProjectsRouteImport
      parentRoute: typeof TempDbRequiredRoute
    }
    '/_tempDbRequired/projects/': {
      id: '/_tempDbRequired/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof TempDbRequiredProjectsIndexRouteImport
      parentRoute: typeof TempDbRequiredProjectsRoute
    }
    '/api/get/boards': {
      id: '/api/get/boards'
      path: '/api/get/boards'
      fullPath: '/api/get/boards'
      preLoaderRoute: typeof ApiGetBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tempDbRequired/projects/$projectId': {
      id: '/_tempDbRequired/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof TempDbRequiredProjectsProjectIdRouteImport
      parentRoute: typeof TempDbRequiredProjectsRoute
    }
  }
}

interface TempDbRequiredProjectsRouteChildren {
  TempDbRequiredProjectsProjectIdRoute: typeof TempDbRequiredProjectsProjectIdRoute
  TempDbRequiredProjectsIndexRoute: typeof TempDbRequiredProjectsIndexRoute
}

const TempDbRequiredProjectsRouteChildren: TempDbRequiredProjectsRouteChildren =
  {
    TempDbRequiredProjectsProjectIdRoute: TempDbRequiredProjectsProjectIdRoute,
    TempDbRequiredProjectsIndexRoute: TempDbRequiredProjectsIndexRoute,
  }

const TempDbRequiredProjectsRouteWithChildren =
  TempDbRequiredProjectsRoute._addFileChildren(
    TempDbRequiredProjectsRouteChildren,
  )

interface TempDbRequiredRouteChildren {
  TempDbRequiredProjectsRoute: typeof TempDbRequiredProjectsRouteWithChildren
}

const TempDbRequiredRouteChildren: TempDbRequiredRouteChildren = {
  TempDbRequiredProjectsRoute: TempDbRequiredProjectsRouteWithChildren,
}

const TempDbRequiredRouteWithChildren = TempDbRequiredRoute._addFileChildren(
  TempDbRequiredRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TempDbRequiredRoute: TempDbRequiredRouteWithChildren,
  ApiBoardsRoute: ApiBoardsRoute,
  ApiCleanupRoute: ApiCleanupRoute,
  ApiGetTempIdRoute: ApiGetTempIdRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiTempDbRoute: ApiTempDbRoute,
  ApiTodoItemsRoute: ApiTodoItemsRoute,
  ApiGetBoardsRoute: ApiGetBoardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
