/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsIndexRouteImport } from './routes/boards.index'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as ApiTempDbRouteImport } from './routes/api.temp-db'
import { Route as ApiGetBoardsRouteImport } from './routes/api.get.boards'

const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsIndexRoute = BoardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsRoute,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardsRoute,
} as any)
const ApiTempDbRoute = ApiTempDbRouteImport.update({
  id: '/api/temp-db',
  path: '/api/temp-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetBoardsRoute = ApiGetBoardsRouteImport.update({
  id: '/api/get/boards',
  path: '/api/get/boards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/api/temp-db': typeof ApiTempDbRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/api/get/boards': typeof ApiGetBoardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/temp-db': typeof ApiTempDbRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards': typeof BoardsIndexRoute
  '/api/get/boards': typeof ApiGetBoardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/api/temp-db': typeof ApiTempDbRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/boards/': typeof BoardsIndexRoute
  '/api/get/boards': typeof ApiGetBoardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/api/temp-db'
    | '/boards/$boardId'
    | '/boards/'
    | '/api/get/boards'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/temp-db' | '/boards/$boardId' | '/boards' | '/api/get/boards'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/api/temp-db'
    | '/boards/$boardId'
    | '/boards/'
    | '/api/get/boards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRouteWithChildren
  ApiTempDbRoute: typeof ApiTempDbRoute
  ApiGetBoardsRoute: typeof ApiGetBoardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/': {
      id: '/boards/'
      path: '/'
      fullPath: '/boards/'
      preLoaderRoute: typeof BoardsIndexRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/api/temp-db': {
      id: '/api/temp-db'
      path: '/api/temp-db'
      fullPath: '/api/temp-db'
      preLoaderRoute: typeof ApiTempDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get/boards': {
      id: '/api/get/boards'
      path: '/api/get/boards'
      fullPath: '/api/get/boards'
      preLoaderRoute: typeof ApiGetBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardsRouteChildren {
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  BoardsIndexRoute: typeof BoardsIndexRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  BoardsIndexRoute: BoardsIndexRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRouteWithChildren,
  ApiTempDbRoute: ApiTempDbRoute,
  ApiGetBoardsRoute: ApiGetBoardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
